### PR TITLE
Add LIGO and update TCCON listing

### PR DESCRIPTION
**Pull request by tmorrell**

### CODE REVIEW

**Comment by mfenner** [comment]
@tmorrell what do you mean by "TCCON not present on landing pages"? The idea of the CSV is to list repos that do exactly that. Should we say "in progress" then?

**Comment by tmorrell** [comment]
Sure, you can leave that line as it was.

On May 17, 2018, at 11:17 PM, Martin Fenner <notifications@github.com<mailto:notifications@github.com>> wrote:


@tmorrell<https://github.com/tmorrell> what do you mean by "TCCON not present on landing pages"? The idea of the CSV is to list repos that do exactly that. Should we say "in progress" then?

**Comment by tmorrell** [comment]
Updated PR to only include LIGO, which is completed

**Comment by mfenner** [comment]
Thanks @tmorrell!

**Pull request merged**
